# Tier 1: the generated Julia. No Julia session needed -- these read the source
# text, which is exactly what makes them cheap enough to run on every change.

src_of <- function(model = toy_model(), blocks = toy_blocks(), ...) {
  et_julia_source(model, blocks, ...)$src
}

test_that("the module is self-contained and correctly delimited", {
  s <- src_of(module_name = "ETRTest")
  expect_match(s, "^# Generated by EpidemicTrajectoriesR")
  expect_match(s, "\nmodule ETRTest\n", fixed = TRUE)
  expect_match(s, "\nend # module ETRTest\n", fixed = TRUE)
  for (u in c("using EpidemicTrajectories", "using PracticalBayes",
              "using PracticalEpiBayes", "import ADTypes")) {
    expect_match(s, u, fixed = TRUE)
  }
})

test_that("the module name is a function of the CONTENT", {
  # Same model, same module: a repeated et_loglik()/et_check_depends()/
  # et_sample() reuses the compiled module instead of recompiling the stack.
  a <- et_julia_source(toy_model(), toy_blocks())
  b <- et_julia_source(toy_model(), toy_blocks())
  expect_equal(a$module, b$module)
  expect_equal(a$src, b$src)
  # A changed model gets a different module.
  m2 <- toy_model(); m2$parameters$alpha <- prior(gamma_dist(2, 2), init = 0.05)
  expect_false(identical(et_julia_source(m2, toy_blocks())$module, a$module))
})

test_that("the header carries no timestamp", {
  # A varying header would make every generation a fresh module and force a
  # full recompile each time.
  expect_false(grepl("\\d{4}-\\d{2}-\\d{2}", strsplit(src_of(), "\n")[[1]][1]))
})

test_that("the state space fixes the encoding", {
  expect_match(src_of(), "const STATES = [:S, :I]", fixed = TRUE)
})

test_that("transitions render in ET's own syntax", {
  s <- src_of()
  expect_match(s, "const TRANS = @transitions STATES begin", fixed = TRUE)
  expect_match(s, "S -> I = et_rate_S_I", fixed = TRUE)
  expect_match(s, "I -> S = et_rate_I_S", fixed = TRUE)
})

test_that("aggregates render with literal dimensions", {
  s <- src_of()
  expect_match(s, "const AGGS = @aggregate STATES begin", fixed = TRUE)
  expect_match(s, sprintf("@array n_infected Int (%d, %d)", TOY_PENS, TOY_T),
               fixed = TRUE)
  expect_match(s, "n_infected[data.group[i], t] += (state == :I)", fixed = TRUE)
})

test_that("payload bindings carry an EXPLICIT element type", {
  # Nothing downstream should depend on how JuliaCall happened to marshal an
  # array: an R integer can arrive as Int32, a one-column matrix as a vector.
  s <- src_of()
  expect_match(s, "const y = Matrix{Int}(Main.", fixed = TRUE)
  expect_match(s, "const group = Vector{Int}(vec(Main.", fixed = TRUE)
})

test_that("payload names are namespaced by module, so two models cannot collide", {
  g <- et_julia_source(toy_model(), toy_blocks())
  expect_true(all(startsWith(names(g$payload), paste0(g$module, "_"))))
  expect_setequal(sub(paste0("^", g$module, "_"), "", names(g$payload)),
                  c("y", "group"))
})

test_that("a vector-returning role gets the parameter-type prologue", {
  s <- src_of()
  expect_match(s, "function et_starting_state(model, data, X, i, t)", fixed = TRUE)
  expect_match(s, "ETR_T = promote_type(eltype(model.nu))", fixed = TRUE)
  expect_match(s, "p = zeros(ETR_T, data.n_states)", fixed = TRUE)
})

test_that("a scalar role converts every returned value to the parameter type", {
  # Otherwise `return(1)` (Int) and `return(1 - theta)` make the Julia return
  # type a Union -- runtime dispatch in the hottest function in the package.
  s <- src_of()
  expect_match(s, "function et_obs_weight(model, data, X, i, t, s)", fixed = TRUE)
  expect_match(s, "return convert(ETR_T, 1)", fixed = TRUE)
  expect_match(s, "convert(ETR_T, (y == 1 ? model.theta : 1 - model.theta))",
               fixed = TRUE)
})

test_that("both likelihood terms are emitted when there is an observation process", {
  s <- src_of()
  expect_match(s, "@addlogprob! loglik_fn(pars, data, X)", fixed = TRUE)
  expect_match(s, "@addlogprob! obs_loglik_fn(pars, data, X)", fixed = TRUE)
  expect_match(s, "et_obsloglik_for(DATA) = epidemic_obs_loglik(DATA)", fixed = TRUE)
})

test_that("a model with no observation process emits only the epidemic term", {
  f <- function(model, data, i, t) 1 / model$m
  d <- suppressMessages(et_data(
    n_individuals = TOY_N, n_timepoints = TOY_T,
    transitions = et_transitions(toy_states, "S -> I" = toy_infection,
                                 "I -> S" = toy_recovery),
    starting_state = toy_start, aggregates = toy_aggregate(),
    group = rep(seq_len(TOY_PENS), each = TOY_PER_PEN)))
  m <- et_model(data = d, parameters = list(
    alpha = prior(gamma_dist(1, 1), init = 0.05),
    beta  = prior(gamma_dist(1, 1), init = 0.05),
    m     = prior(gamma_dist(2, 4), init = 5.0),
    nu    = prior(beta_dist(1, 1), init = 0.1)))
  s <- et_julia_source(m)$src
  expect_match(s, "@addlogprob! loglik_fn(pars, data, X)", fixed = TRUE)
  expect_false(grepl("obs_loglik_fn", s, fixed = TRUE))
  expect_false(grepl("OBSLOGLIK", s, fixed = TRUE))
})

test_that("priors, deterministics and the trajectory block render in the model", {
  s <- src_of()
  expect_match(s, "alpha ~ Gamma(1.0, 1.0)", fixed = TRUE)
  expect_match(s, "m_tilde ~ Gamma(2.0, 4.0)", fixed = TRUE)
  expect_match(s, "m := m_tilde + 1", fixed = TRUE)
  expect_match(s, sprintf("X ~ TrajectoryLatent(%d, %d)", TOY_T, TOY_N),
               fixed = TRUE)
  # `pars` carries the derived name, because that is what the rate reads.
  expect_match(s, "m=m", fixed = TRUE)
})

test_that("a vector parameter becomes filldist", {
  d <- toy_data()
  m <- et_model(data = d, parameters = list(
    alpha = prior(beta_dist(1, 1), init = rep(0.5, 3), n = 3),
    nu = prior(beta_dist(1, 1), init = 0.1), theta = prior(beta_dist(1, 1), init = 0.5),
    beta = prior(beta_dist(1,1), init = 0.1), m = prior(gamma_dist(2,4), init = 5)))
  expect_match(et_julia_source(m)$src,
               "alpha ~ PracticalBayes.filldist(Beta(1.0, 1.0), 3)", fixed = TRUE)
})

test_that("the params closure re-derives deterministics from the Gibbs state", {
  expect_match(src_of(),
               "et_params(v) = (; alpha=v.alpha, beta=v.beta, m_tilde=v.m_tilde, nu=v.nu, theta=v.theta, m=v.m_tilde + 1)",
               fixed = TRUE)
})

test_that("Gibbs blocks render to their kernels", {
  s <- src_of()
  expect_match(s, "(:alpha, :beta, :m_tilde) => NUTS(0.8)", fixed = TRUE)
  expect_match(s, ":X => iffbs_kernel(LATENT!; params=et_params)", fixed = TRUE)
  expect_match(s, "test_sensitivity_kernel(:theta; Y=y, infected_state=2",
               fixed = TRUE)
  expect_match(s, "initial_state_kernel(:nu; at=1", fixed = TRUE)
  # State NAMES are resolved to the indices ET uses.
  expect_match(s, "states=(1, 2)", fixed = TRUE)
})

test_that("an HMC block renders its metric", {
  m <- toy_model()
  b <- list(et_hmc(c("alpha", "beta", "m_tilde"), n_steps = 15,
                   step_size = list(alpha = 0.01, beta = 0.02, m_tilde = 0.1)),
            et_conjugate_initial_state("nu", at = 1, states = c("S", "I")),
            et_conjugate_test_sensitivity("theta", y = "y", infected_state = "I"))
  s <- et_julia_source(m, b)$src
  expect_match(s, "HMC(15; integrator=Leapfrog(1.0)", fixed = TRUE)
  expect_match(s, "DiagEuclideanMetric(Float64[0.01, 0.02, 0.1] .^ 2)", fixed = TRUE)
})

test_that("a raw Julia kernel is passed straight through", {
  m <- toy_model()
  b <- c(toy_blocks(), list(et_kernel_julia("alpha", "MyKernel(1.0)")))
  b <- b[!vapply(b, function(x) identical(x$vars, c("alpha", "beta", "m_tilde")),
                 logical(1))]
  b <- c(b, list(et_nuts(c("beta", "m_tilde"))))
  expect_match(et_julia_source(m, b)$src, ":alpha => MyKernel(1.0)", fixed = TRUE)
})

test_that("the entry gate is emitted only when asked for, with its survival", {
  f <- function(model, data, i, t) 1
  surv <- function(model, data, i, t) exp(-model$c1)
  d <- et_data(
    n_individuals = TOY_N, n_timepoints = TOY_T,
    transitions = et_transitions(c("S", "I", "D"),
                                 "S -> I" = toy_infection,
                                 survival = et_survival(surv, death = "D")),
    starting_state = toy_start,
    aggregates = et_aggregate(c("S", "I", "D"),
      arrays = list(n_infected = et_array("Int", c(TOY_PENS, TOY_T))),
      update = function(model, data, X, state, i, t) {
        n_infected[data$group[i], t] <- n_infected[data$group[i], t] + (state == "I")
      }),
    group = rep(seq_len(TOY_PENS), each = TOY_PER_PEN),
    observation_weight = toy_obs,
    extras = list(y = toy_y(), entry = rep(1L, TOY_N)))
  m0 <- et_model(data = d, parameters = list(
    alpha = prior(gamma_dist(1, 1), init = 0.05), beta = prior(gamma_dist(1, 1), init = 0.05),
    nu = prior(beta_dist(1, 1), init = 0.1), theta = prior(beta_dist(1, 1), init = 0.5),
    c1 = prior(exponential_dist(1), init = 0.1)))
  expect_match(et_julia_source(m0)$src, "et_loglik_for(DATA) = epidemic_loglik(DATA)",
               fixed = TRUE)

  m1 <- et_model(data = d, parameters = m0$parameters, entry_time = "entry")
  expect_match(et_julia_source(m1)$src,
               "epidemic_loglik(DATA; entry_time=Vector{Int}(entry), survival=et_survival_fn)",
               fixed = TRUE)
  # @survival must reach ET's macro with the death state named.
  expect_match(et_julia_source(m1)$src, "@survival et_survival_fn death=:D",
               fixed = TRUE)
})

test_that("a separate likelihood weight is wired to epidemic_obs_loglik", {
  filt <- function(model, data, X, i, t, s) model$eta * toy_obs(model, data, X, i, t, s)
  d <- et_data(
    n_individuals = TOY_N, n_timepoints = TOY_T,
    transitions = et_transitions(toy_states, "S -> I" = toy_infection,
                                 "I -> S" = toy_recovery),
    starting_state = toy_start, aggregates = toy_aggregate(),
    group = rep(seq_len(TOY_PENS), each = TOY_PER_PEN),
    observation_weight = filt, likelihood_weight = toy_obs,
    helpers = list(et_helper(toy_obs, "toy_obs")),
    extras = list(y = toy_y()))
  m <- et_model(data = d, parameters = list(
    alpha = prior(gamma_dist(1, 1), init = 0.05), beta = prior(gamma_dist(1, 1), init = 0.05),
    m = prior(gamma_dist(2, 4), init = 5), nu = prior(beta_dist(1, 1), init = 0.1),
    theta = prior(beta_dist(1, 1), init = 0.5), eta = prior(beta_dist(1, 1), init = 0.3)))
  g <- et_julia_source(m)
  expect_match(g$src,
               "epidemic_obs_loglik(DATA; observation_weight=et_obs_lik_weight)",
               fixed = TRUE)
  # `eta` is in the FILTER only, so it must not appear in the observation term's
  # dependency set -- the filter is never differentiated.
  expect_false("eta" %in% g$depends$observation)
  expect_true("theta" %in% g$depends$observation)
})

test_that("time-varying affected lists are built in the generated module", {
  gm <- matrix(rep(seq_len(TOY_PENS), each = TOY_PER_PEN), TOY_N, TOY_T)
  storage.mode(gm) <- "integer"
  d <- et_data(
    n_individuals = TOY_N, n_timepoints = TOY_T,
    transitions = et_transitions(toy_states, "S -> I" = toy_infection,
                                 "I -> S" = toy_recovery),
    starting_state = toy_start, aggregates = toy_aggregate(),
    group = rep(seq_len(TOY_PENS), each = TOY_PER_PEN),
    observation_weight = toy_obs,
    affected_individuals = et_affected_from_groups(gm),
    extras = list(y = toy_y()))
  m <- et_model(data = d, parameters = toy_model()$parameters,
                derived = list(m = quote(m_tilde + 1)))
  s <- et_julia_source(m)$src
  expect_match(s, "const affected_individuals = let gm = affected_groups", fixed = TRUE)
  expect_match(s, "affected_individuals=affected_individuals", fixed = TRUE)
  # The focal must be excluded from its own list, matching ET's default.
  expect_match(s, "[j for j in by_group[g, t] if j != i]", fixed = TRUE)
})

test_that("a conjugate-owned parameter gets a placeholder distribution", {
  d <- toy_data()
  m <- et_model(data = d, parameters = list(
    alpha = prior(gamma_dist(1, 1), init = 0.05), beta = prior(gamma_dist(1, 1), init = 0.05),
    m = prior(gamma_dist(2, 4), init = 5), theta = prior(beta_dist(1, 1), init = 0.5),
    nu = prior(init = c(0.05, 0.05, 0.05, 0.05), dim = c(2, 2), kind = "latent")))
  b <- list(et_conjugate_initial_state("nu", at = c(1, 2), states = c("S", "I"), n = 2),
            et_conjugate_test_sensitivity("theta", y = "y", infected_state = "I"))
  s <- et_julia_source(m, b)$src
  expect_match(s, "struct _ETPlaceholder_nu <: Distributions.DiscreteMatrixDistribution end",
               fixed = TRUE)
  expect_match(s, "Distributions.logpdf(::_ETPlaceholder_nu, ::AbstractMatrix) = 0.0",
               fixed = TRUE)
  expect_match(s, "nu ~ _ETPlaceholder_nu()", fixed = TRUE)
})

test_that("a vector or scalar latent parameter is refused with a useful message", {
  d <- toy_data()
  m <- et_model(data = d, parameters = list(
    alpha = prior(gamma_dist(1, 1), init = 0.05),
    nu = prior(init = c(0.1, 0.2), n = 2, kind = "latent")))
  expect_error(et_julia_source(m, list(
    et_conjugate("nu", "beta", c(1, 1), function(X, data, k) c(1, 1), n = 2))),
    "matrix-valued")
})

test_that("et_julia() bodies pass through and suppress depends= derivation", {
  d <- toy_data()
  d$observation_weight <- et_julia("return one(Float64)")
  m <- et_model(data = d, parameters = toy_model()$parameters,
                derived = list(m = quote(m_tilde + 1)))
  g <- et_julia_source(m)
  expect_match(g$src, "return one(Float64)", fixed = TRUE)
  # Unscannable body -> no annotation, which is PracticalBayes' safe default.
  expect_null(g$depends$observation)
  expect_false(grepl("obs_loglik_fn(pars, data, X)  depends", g$src, fixed = TRUE))
  # The epidemic term is unaffected and keeps its annotation.
  expect_false(is.null(g$depends$epidemic))
})

test_that("an et_julia() body WITH declared reads keeps the annotation", {
  d <- toy_data()
  d$observation_weight <- et_julia("return one(eltype(model.theta))",
                                   reads = "theta")
  m <- et_model(data = d, parameters = toy_model()$parameters,
                derived = list(m = quote(m_tilde + 1)))
  g <- et_julia_source(m)
  expect_equal(sort(g$depends$observation), sort(c("theta", "X")))
})

test_that("the generated runner and validator are present", {
  s <- src_of()
  expect_match(s, "function et_run(", fixed = TRUE)
  expect_match(s, "function et_loglik_at(", fixed = TRUE)
  expect_match(s, "function et_iffbs_sweep(", fixed = TRUE)
  expect_match(s, "function et_check_depends(", fixed = TRUE)
  # The aggregates must agree with the STARTING trajectory before the first
  # likelihood call; that invariant is established once, here.
  expect_match(s, "reset_aggregates!(DATA)", fixed = TRUE)
  expect_match(s, "apply_derived_summaries!(et_params(INIT_PARS), DATA, X0)",
               fixed = TRUE)
  # The AD backend is a runtime argument, not a compile-time constant.
  expect_match(s, "adtype=ADTypes.AutoForwardDiff()", fixed = TRUE)
})
